schema: ${NEXT_PUBLIC_SALEOR_HOST_URL}/graphql/
documents: graphql/**/*.graphql
extensions:
  codegen:
    overwrite: true
    generates:
      generated/graphql.ts:
        plugins:
          - typescript
          - typescript-operations
          - urql-introspection
          - typescript-urql
      ./generated/graphql.schema.json:
        plugins:
          - "introspection"
      generated/schema.graphql:
        plugins:
          - schema-ast